### PR TITLE
Compatibility to Laravel 7.x

### PR DESCRIPTION
**Pull request by leMaur**
This PR will make the package compatible with Laravel 7.x :wink:

### CODE REVIEW

**Comment by freekmurze** [comment]
It seems like the testsuite is failing on the lower dependancies. Could you take a look at that? Feel free to require higher versions of packages to fix this. I'd be willing to create a new major release of this package of that would help.

**Comment by leMaur** [comment]
Yes, I can take a look during the weekend.
I agree with you, create a major release with higher versions of packages
could be a solution.
I will go in this direction to fix the PR!

**Comment by sandervanhooft** [comment]
@freekmurze Gentle reminder from your Dutch neighbor 👋.
This PR seems ready to be merged.

**Comment by freekmurze** [comment]
@sandervanhooft Howdy neighbour. Thanks for this, I'll create a new major release later today!

**Comment by freekmurze** [comment]
Thanks @leMaur

**Pull request merged**
